### ISSUE TITLE
Uncaught TypeError: Cannot read property 'appendMorph' of undefined

### ISSUE THREAD

**Issue by artsyca** [emberui/emberui#101]
Steps to reproduce:
1. `eui-datepicker` with Ember 1.13
2. Click on the button.
3. Get the error `Uncaught TypeError: Cannot read property 'appendMorph' of undefined`

![screen shot 2015-09-21 at 4 56 41 pm](https://cloud.githubusercontent.com/assets/364015/10004860/fe49038c-6081-11e5-9e8f-f117cd9072ea.png)

Expected behaviour

See the calendar widget.

**Comment by kenips** [comment]
Chalked up some ideas on this at d947058 but I haven't looked into compatibility nor tests yet.

**Comment by jacojoubert** [comment]
The plan is to move to ember-wormhole instead of this custom hack. Just waiting on ember-collections to land so I can start the work on ember 2.0 compatibility.

**Comment by kenips** [comment]
Ha! Same thought here :-), but unfortunately ember-wormhole doesn't inject into body. I stole the body injection from here https://github.com/yapplabs/ember-wormhole/pull/16#issuecomment-125239406

**Comment by jacojoubert** [comment]
Seems pretty simple to update. This requires glimmer I take it? So it will break under ember 1.12

**Comment by kenips** [comment]
That's my assumption too (glimmer enables moving DOM trees like this). Hence I haven't PR'd this - maybe needs a full update on deprecation and cut a new version?
