### ISSUE TITLE
error running emberui

### ISSUE THREAD

**Issue by cescarpa** [emberui/emberui#102]
Cloned the repository, installed dependencies. Running ember server or ember tests i get this error:
.......
EEXIST, file already exists '/home/.../emberui/tmp/coffee_script_filter-tmp_dest_dir-MBEPhi45.tmp/dummy/router.js'
......
at /home/.../emberui/node_modules/ember-cli-coffeescript/node_modules/broccoli-filter/index.js:45:11
.....
at process._tickCallback (node.js:355:11)
.....

Environment:

Ember version: 1.13.8
node: 0.12.2
npm: 2.13.4
os: linux x64

**Comment by jacojoubert** [comment]
Do you perchance have a router.js file in your tests/dummy/app folder? That error happens when you have a .js and a .coffee file with the same name.

**Comment by cescarpa** [comment]
yeap, that was the issue. The file comes with the repository.

Thank so much. I am triying to deploy an app using emberui in a tablet as a cordova application. 
I currently use the standard ember widgets but i wish i could use emberui in order to gain functionality and modularity for the application. Hope i can somehow contribute your project. 
Thanks for your effort.
