### ISSUE TITLE
EMBERUI css is not getting added to vendor.css

### ISSUE THREAD

**Issue by kishorekpoluri** [emberui/emberui#106]
on build or ember serve, css from emberui is not getting added to vendor.css in dist/assets

**Comment by jacojoubert** [comment]
Sorry about the delay in responding. I was on vacation.

You need in manually include the css into your app via:

```scss
@import "emberui";
@include emberui-theme();
```

I am in the process of improving how theming works and this allows you to create new styles via importing of mixins. This apples as of `1.0.0-beta.5`
