### ISSUE TITLE
Canary + Handlebars 2

### ISSUE THREAD

**Issue by dioptre** [emberui/emberui#81]
Hi Guys,

I had a dependency from firebase requiring me to upgrade, now ember ui won't work. I had a crack at hacking the code, but will need longer than I can take to fix it. Please help!

Thanks
Andy

**Comment by ahmadsoe** [comment]
@kenips I'm still getting this error on Handlebars 2.0
`Uncaught TypeError: Cannot set property 'compilerInfo' of undefined`

**Comment by kenips** [comment]
@ahmadsoe you can use https://github.com/kenips/emberui/tree/support/ember_19_dist for now. I'm still waiting for official release of all the pieces then I'll do a PR. Note that this only works with 1.9 but not 1.10 nor canary.

**Comment by ahmadsoe** [comment]
@kenips any chances to make it work on canary build? I'm having another addons that won't work with ember 1.9.

**Comment by kenips** [comment]
@ahmadsoe you can try https://github.com/kenips/emberui/tree/support/ember_110_dist

**Comment by kenips** [comment]
This issue should be closed by 0.6.0
