### ISSUE TITLE
Not all modules are being exported in named amd?

### ISSUE THREAD

**Issue by artsyca** [emberui/emberui#91]
Steps to reproduce:

Using the named-amd build in ember-cli, attempting to import `EuiButtonTemplate`:

  `import { EuiButtonComponent, EuiButtonTemplate } from 'emberui'`

This is necessary for registering with the container during testing. However, `EuiButtonTemplate` is always undefined.

Looking at the dist, around line [1421](https://github.com/emberui/emberui/blob/master/dist/named-amd/emberui.js#L1421), it seems that many items are being imported, but not all are being included in the `__exports__`

Just opening this issue to confirm that the intention is that all modules are exported?

**Comment by ghedamat** [comment]
@artsyca iirc yah that was the intention, during some refactoring for a long running PR that should turn emberui into an ember-cli addon I noticed that some where missing

see https://github.com/emberui/emberui/blob/master/lib/emberui.js#L58-L70

we should probably add all that is needed to those exports to support people that use the amd build without the addon (when we merge #87)

wanna take a quick stub at adding those? 

/cc @elucid

**Comment by artsyca** [comment]
Yes absolutely! Will send a PR today.
