### ISSUE TITLE
Radio buttons

### ISSUE THREAD

**Issue by xypaul** [emberui/emberui#93]
And plans to support radio buttons?

**Comment by zachaysan** [comment]
I remember we talked about it a while ago. I think we came to the conclusion that for most cases a Select should do just fine. The only place we thought it might have an edge would be for something like a survey where you have a grid of answers. So if it goes in, it probably won't be for a while, and @jacojoubert would probably need to hear a passionate case for including them. Or you could try buying him something fancy :gem: :smile:

**Comment by jacojoubert** [comment]
Radio buttons doesn't have much place in good design in my opinion. Even for something like a survey i am not convinced a radio button is the way to, instead of selectable/clickable blocks. Functionally the same as a radio buttons, visually worlds apart.

**Comment by xypaul** [comment]
Arguments for radio buttons:
- One click instead of two
- Preview off all the options

I still think radio buttons have an important role in web design. It's also interesting to note that there is currently no awesome implementation in the ember community for radio buttons. Would be cool if emberui was a leader in this.
